### ISSUE TITLE
Nice one!

### ISSUE THREAD

**Issue by FGRibreau** [compybara/redis-benchmarks-ui#1]
Nice one @compybara !

Your benchmark ui will be shared in our next [RedisWeekly](http://redisweekly.com) :)!

**Comment by compybara** [comment]
Awesome, thanks! 

It's still a work in progress, but I'm glad someone finds it useful! This is my first foray into node.js web development so any feedback or tips are welcome.

**Comment by FGRibreau** [comment]
:+1
